version: '3.1'
services:
  mojaBazaSpremnik:
    image: 'filmovi/orlabosi:baza'
    build: .
    container_name: filmoviContainer
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=neverMinD44
    ports:
      - "5435:5432"
