version: "3.9"

services:
  backend:
    build: ./backend
    container_name: filmovi_backend
    ports:
      - "4455:4455"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: neverMinD44
      DB_NAME: filmovi
      DB_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: filmovi_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: neverMinD44
      POSTGRES_DB: filmovi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./filmovi.sql:/docker-entrypoint-initdb.d/filmovi.sql


volumes:
  pgdata:
